'use client';

import React from 'react';
import Link from 'next/link';
import Navbar from '@/components/Navbar';
import { ShieldCheck, Award, FileText, CheckCircle2, ChevronRight, Play, Terminal } from 'lucide-react';

export default function LandingPage() {
  return (
    <>
      <Navbar />
      <main style={styles.main}>
        {/* Hero Section */}
        <section style={styles.hero}>
          <div style={styles.badge}>
            <span style={styles.badgeText}>🚀 Z.AI Recruitment Assistant</span>
          </div>
          
          <h1 style={styles.title}>
            Screen Smarter.<br />
            <span className="gradient-text">Discover Candidates</span><br />
            Who Actually Match.
          </h1>
          
          <p style={styles.subtitle}>
            AI-powered resume, portfolio, and project analysis for evidence-based candidate screening. 
            Don't just read resumes. Verify their GitHub and project code evidence automatically.
          </p>

          <div style={styles.ctaGroup}>
            <Link href="/register" className="btn btn-primary btn-lg" style={styles.ctaBtn}>
              Create a Job <ChevronRight size={18} />
            </Link>
            <Link href="/login?demo=recruiter" className="btn btn-secondary btn-lg" style={styles.ctaBtn}>
              <Play size={16} fill="currentColor" /> View Demo Mode
            </Link>
          </div>
        </section>

        {/* Value Proposition Grid */}
        <section style={styles.section}>
          <h2 style={styles.sectionTitle}>Evidence-Based Applicant Verification</h2>
          <p style={styles.sectionSubtitle}>
            Our platform does not rely on simple resume keyword matches. We mathematically score applicants by tracing their claimed skills to actual code evidence.
          </p>

          <div style={styles.grid}>
            <div className="glass-panel" style={styles.card}>
              <div style={styles.iconWrapper}>
                <FileText size={24} color="var(--accent-blue)" />
              </div>
              <h3 style={styles.cardTitle}>1. Analyze Job Requirements</h3>
              <p style={styles.cardText}>
                Upload a job description. The AI automatically parses required and preferred skills, calculates priority weights, and defines matching metrics.
              </p>
            </div>

            <div className="glass-panel" style={styles.card}>
              <div style={styles.iconWrapper}>
                <Terminal size={24} color="var(--accent-purple)" />
              </div>
              <h3 style={styles.cardTitle}>2. Code & Portfolio Audit</h3>
              <p style={styles.cardText}>
                Connect the candidate's GitHub. The verifier scans package manifests, file routing paths, test suites, and Dockerfiles to verify resume claims.
              </p>
            </div>

            <div className="glass-panel" style={styles.card}>
              <div style={styles.iconWrapper}>
                <ShieldCheck size={24} color="var(--accent-cyan)" />
              </div>
              <h3 style={styles.cardTitle}>3. Claim Verification Engine</h3>
              <p style={styles.cardText}>
                Assigns status indicators (Supported, Partially Supported, Not Verified) directly referencing file structures, removing false confidence.
              </p>
            </div>

            <div className="glass-panel" style={styles.card}>
              <div style={styles.iconWrapper}>
                <Award size={24} color="var(--match-excellent)" />
              </div>
              <h3 style={styles.cardTitle}>4. Job-Specific Ranking</h3>
              <p style={styles.cardText}>
                Rank candidates using a multi-dimensional score (ATS, Portfolio, Technical Evidence, Gaps) calculated dynamically for each distinct role.
              </p>
            </div>
          </div>
        </section>

        {/* Proof Section */}
        <section className="glass-panel" style={styles.evidenceBanner}>
          <div style={styles.bannerContent}>
            <h3 style={styles.bannerTitle}>"Don't Just Read the Resume. Verify the Evidence."</h3>
            <p style={styles.bannerText}>
              Every score generated by TalentLens AI includes specific evidence citations. Compare claims directly against source repositories, allowing HR to make faster, evidence-backed hiring decisions.
            </p>
            <div style={styles.evidenceMock}>
              <div style={styles.mockHeader}>
                <span style={styles.mockDot}></span>
                <span style={styles.mockDot}></span>
                <span style={styles.mockDot}></span>
                <span style={{ color: 'var(--text-muted)', fontSize: '0.75rem', marginLeft: '12px' }}>Resume & Portfolio Verification Engine</span>
              </div>
              <div style={styles.mockBody}>
                <div style={styles.mockItem}>
                  <div style={styles.mockClaim}>💬 <strong>Claim:</strong> "Developed a production-grade REST API."</div>
                  <div style={styles.mockStatus} className="score-badge score-excellent btn-sm">Verified Supported</div>
                  <div style={styles.mockEvidence}>🔍 <strong>Evidence:</strong> Express API routes, JWT authentication middleware, and database schemas found in <code>server-api/src/routes/auth.ts</code>.</div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
      
      <footer style={styles.footer}>
        <div style={styles.footerContainer}>
          <span style={styles.footerText}>© 2026 TalentLens AI. All rights reserved. Powered by Z.AI Recruitment Intelligence.</span>
        </div>
      </footer>
    </>
  );
}

const styles = {
  main: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '0 24px',
  },
  hero: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    textAlign: 'center' as const,
    padding: '80px 0 60px 0',
  },
  badge: {
    background: 'rgba(59, 130, 246, 0.1)',
    border: '1px solid rgba(59, 130, 246, 0.25)',
    borderRadius: 'var(--radius-full)',
    padding: '6px 16px',
    marginBottom: '24px',
  },
  badgeText: {
    fontSize: '0.85rem',
    fontWeight: 600,
    color: 'var(--accent-blue)',
    letterSpacing: '0.02em',
  },
  title: {
    fontSize: '3.6rem',
    lineHeight: '1.15',
    marginBottom: '24px',
    fontWeight: 800,
    fontFamily: 'var(--font-display)',
    letterSpacing: '-0.03em',
  },
  subtitle: {
    maxWidth: '700px',
    fontSize: '1.15rem',
    color: 'var(--text-secondary)',
    marginBottom: '40px',
    lineHeight: '1.7',
  },
  ctaGroup: {
    display: 'flex',
    gap: '16px',
    flexWrap: 'wrap' as const,
    justifyContent: 'center',
  },
  ctaBtn: {
    padding: '14px 28px',
    fontSize: '1rem',
  },
  section: {
    padding: '60px 0',
  },
  sectionTitle: {
    textAlign: 'center' as const,
    fontSize: '2rem',
    marginBottom: '12px',
  },
  sectionSubtitle: {
    textAlign: 'center' as const,
    maxWidth: '700px',
    margin: '0 auto 48px auto',
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))',
    gap: '24px',
  },
  card: {
    padding: '32px',
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'flex-start',
    gap: '16px',
  },
  iconWrapper: {
    background: 'rgba(255, 255, 255, 0.03)',
    border: '1px solid var(--border-color)',
    borderRadius: 'var(--radius-md)',
    padding: '12px',
  },
  cardTitle: {
    fontSize: '1.2rem',
    fontWeight: 600,
  },
  cardText: {
    fontSize: '0.9rem',
    color: 'var(--text-secondary)',
    lineHeight: '1.6',
  },
  evidenceBanner: {
    margin: '60px 0 100px 0',
    padding: '48px',
    background: 'radial-gradient(ellipse at top right, rgba(139, 92, 246, 0.1), transparent), radial-gradient(ellipse at bottom left, rgba(59, 130, 246, 0.08), transparent), var(--bg-card)',
  },
  bannerContent: {
    maxWidth: '900px',
    margin: '0 auto',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '20px',
  },
  bannerTitle: {
    fontSize: '1.8rem',
    color: 'var(--text-primary)',
  },
  bannerText: {
    fontSize: '1.05rem',
    color: 'var(--text-secondary)',
    lineHeight: '1.7',
  },
  evidenceMock: {
    background: 'rgba(5, 7, 16, 0.9)',
    border: '1px solid var(--border-color)',
    borderRadius: 'var(--radius-md)',
    marginTop: '20px',
    overflow: 'hidden',
  },
  mockHeader: {
    background: 'rgba(255, 255, 255, 0.02)',
    borderBottom: '1px solid var(--border-color)',
    padding: '12px 16px',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  mockDot: {
    width: '10px',
    height: '10px',
    borderRadius: '50%',
    display: 'inline-block',
    background: 'rgba(255, 255, 255, 0.15)',
  },
  mockBody: {
    padding: '20px',
  },
  mockItem: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '12px',
    alignItems: 'flex-start',
  },
  mockClaim: {
    fontSize: '0.95rem',
  },
  mockStatus: {
    padding: '4px 10px',
    fontSize: '0.75rem',
    borderRadius: 'var(--radius-full)',
  },
  mockEvidence: {
    background: 'rgba(59, 130, 246, 0.04)',
    border: '1px solid rgba(59, 130, 246, 0.1)',
    borderRadius: 'var(--radius-sm)',
    padding: '12px',
    fontSize: '0.9rem',
    width: '100%',
    lineHeight: '1.5',
    color: 'var(--text-secondary)',
  },
  footer: {
    borderTop: '1px solid var(--border-color)',
    padding: '32px 0',
    marginTop: 'auto',
    backgroundColor: 'rgba(7, 9, 19, 0.5)',
  },
  footerContainer: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '0 24px',
    textAlign: 'center' as const,
  },
  footerText: {
    fontSize: '0.8rem',
    color: 'var(--text-muted)',
  },
};
